### ISSUE TITLE
SwiftPackage manager error

### ISSUE THREAD

**Issue by lassestolley** [simla-tech/Fastis#10]
When I try to add the package with the Swift Package Manager in Xcode I get an error: `invalidMainfestFormat`. You have to change this `platforms: [ .iOS(.v13) ]` to this `platforms: [ .iOS(.v12) ]` in the Package.swift file.

**Comment by jis248** [comment]
same issue on my side, 
How did you solve it?

**Comment by ilia3546** [comment]
Hi there! This issue was fixed in the 2.0 version. Please check it :)
