### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by raghavnaphade** [simla-tech/Fastis#12]
While changing its appearance to dark mode, the color of the title of the date picker is not changing.
<img width="453" alt="Screenshot 2022-04-29 at 3 23 17 PM" src="https://user-images.githubusercontent.com/84921664/165923307-fecd8de7-c689-4f65-ba13-f66d05ce7dd2.png">
<img width="466" alt="Screenshot 2022-04-29 at 3 23 26 PM" src="https://user-images.githubusercontent.com/84921664/165923325-91b26147-74b6-4fc5-ba74-3e58a129a6c4.png">

**Comment by ilia3546** [comment]
Hi there! This issue was fixed in the 2.0 version. Please check it :)
