### ISSUE TITLE
There is issue in segmented mode

### ISSUE THREAD

**Issue by Rashmi-hub** [simla-tech/Fastis#18]
- when last day of month is ended on last week(on Sunday)  then multiple date segments are created.
![Simulator Screen Shot - iPhone 13 - 2022-09-12 at 12 05 20](https://user-images.githubusercontent.com/108028232/189589119-12176d67-9287-4486-ab28-d795f7bdc406.png)

**Comment by ilia3546** [comment]
Hello! Also, I noticed that weekdays in the header are not equal to the calendar layout. Please check version 2.2.0

**Comment by Rashmi-hub** [comment]
Still facing the same issue if weekdays are according to the calendar layout.
Please check for the "segmented" mode, 
monthView.rangeSelectionMode = .segmented
![Simulator Screen Shot - iPhone 13 - 2022-09-12 at 16 35 57](https://user-images.githubusercontent.com/108028232/189638999-02371c9b-a6a4-4a5d-b636-8166107fcca5.png)

**Comment by ilia3546** [comment]
Em... This library doesn't support the segmented selection mode :) I guess in this mode underlying library [JTAppleCalendar](https://github.com/patchthecode/JTAppleCalendar) splits up the selected range by months.
To implement this mode, we should rework all logic about result formatting, closures and many other things. But if you want to customise this behaviour, be free to make a fork or create PR ;)

**Comment by Rashmi-hub** [comment]
Okay Thankyou
