### ISSUE TITLE
Date is fine, But it returns wrong time. 

### ISSUE THREAD

**Issue by harooniqbal1993** [simla-tech/Fastis#21]
It always gives 19:00:00 +0000. 

I want current time, is there any fix for this?

**Comment by UriyDevyataev** [comment]
You can update the time in the received date in the method (for example didSelectDate) of the JTACMonthViewDelegate delegate. For example using DateComponents:

```
public func calendar(
        _ calendar: JTACMonthView,
        didSelectDate date: Date,
        cell: JTACDayCell?,
        cellState: CellState,
        indexPath: IndexPath
    ) {

let nowTimeComponents = self.config.calendar.dateComponents([.hour, .minute, .second], from: Date())
var dateComponents = self.config.calendar.dateComponents([.year, .month, .day], from: date)

dateComponents.hour = nowTimeComponents.hour
dateComponents.minute = nowTimeComponents.minute
dateComponents.second = nowTimeComponents.second

//        dateComponents.hour = 10
//        dateComponents.minute = 20
//        dateComponents.second = 30

let newDate = self.config.calendar.date(from: dateComponents)
        
    }
```

**Comment by UriyDevyataev** [comment]
You can update the time in the received date in the method (for example didSelectDate) of the JTACMonthViewDelegate delegate. For example using DateComponents:

`public func calendar(_ calendar: JTACMonthView, didSelectDate date: Date, cell: JTACDayCell?, cellState: CellState, indexPath: IndexPath) {

        let nowTimeComponents = self.config.calendar.dateComponents([.hour, .minute, .second], from: Date())
        var dateComponents = self.config.calendar.dateComponents([.year, .month, .day], from: date)

        dateComponents.hour = nowTimeComponents.hour
        dateComponents.minute = nowTimeComponents.minute
        dateComponents.second = nowTimeComponents.second

        //        dateComponents.hour = 10
        //        dateComponents.minute = 20
        //        dateComponents.second = 30

        let newDate = self.config.calendar.date(from: dateComponents)
    }`
