### ISSUE TITLE
Swift UI

### ISSUE THREAD

**Issue by subashz** [simla-tech/Fastis#22]
Anyway to use this library (plug and play) for swift ui ? Any example will be helpful.

**Comment by UriyDevyataev** [comment]
You can use the library in a Swif UI project using the UIViewControllerRepresentable protocol.
Here is an example:
https://developer.apple.com/tutorials/swiftui/interfacing-with-uikit

**Comment by UriyDevyataev** [comment]
Hi. 
Now we have added an implementation for SwiftUI.
You can read in ReadMe how to use it in your project.
https://github.com/simla-tech/Fastis/pull/54
