### ISSUE TITLE
Add possibility to select range within same day

### ISSUE THREAD

**Issue by dalmaracz** [simla-tech/Fastis#37]
I have the requirement for the user to be able to select a date range so that start and end are within the same date (end to be start + 3hours). Is this currently possible in .range mode? I found that selecting start and end on the same date, returns nil for range.

**Comment by UriyDevyataev** [comment]
Hello!
No. In this version, range selection is available only by day.

**Comment by UriyDevyataev** [comment]
Selecting a start and end on the same date returns a range with a start of 00:00 and an end of 23:59 of the selected day.
If you need time selection functionality, then it is not there.
