### ISSUE TITLE
Done button not visible in iOS 17.0

### ISSUE THREAD

**Issue by almin1337** [simla-tech/Fastis#48]
Hello,

It seems that done button is not visible in iOS versions above 17.0. 
Does anyone have an idea what is the issue?

**Comment by AJereli** [comment]
Same for me

**Comment by AJereli** [comment]
@almin1337 
In my case, the error was on my side. I showed FastisController through a wrapper in SwiftUI, and the controller was not located inside the UINavigationController, as a result the button was not displayed

**Comment by UriyDevyataev** [comment]
Hi, Yes, иuttons might not appear when used in SwiftUI.
Now we have added an implementation for SwiftUI.
You can read in ReadMe how to use it in your project.
https://github.com/simla-tech/Fastis/pull/54
