### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by wlxo0401** [simla-tech/Fastis#49]
Doesn't Fastis need a Privacy Manifest?

**Comment by UriyDevyataev** [comment]
Hi, Fastis is not on the list, so we don't need a a Privacy Manifest. 
https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by wlxo0401** [comment]
> Hi, Fastis is not on the list, so we don't need a a Privacy Manifest. 
> 
> https://developer.apple.com/support/third-party-SDK-requirements/

Thank you for your response.🤩
