### ISSUE TITLE
Cannot infer type of closure parameter 'action' without a type annotation

### ISSUE THREAD

**Issue by allakin** [simla-tech/Fastis#59]
I can't get data range in dismissHandler and sent to currentValue

![CleanShot 2024-06-01 at 16 49 27@2x](https://github.com/simla-tech/Fastis/assets/7867932/de21d4f4-6c9a-4f58-b51b-4eed1322ce9c)

**Comment by allakin** [comment]
Solved a problem through doneHandler method

`swift
	fastisController.doneHandler = { [weak self] date in
			if let newValue = date {
				currentValue = newValue 
			}
		}
`

**Comment by UriyDevyataev** [comment]
Hello. 
What data type is currentValue?
it must conform to the FastisValue protocol
